{{- $udcaName := "apigee-udca" -}}
{{- $values := .Values -}}
{{- $chart := .Chart -}}
{{- $files := .Files -}}
{{- $release := .Release -}}
{{- range $i, $env := .Values.envs -}}
{{- if eq $env.name  $values.env -}}
{{- $generatedName := include "envScopeEncodedName" (dict "org" $values.org "env" $env.name) -}}
{{- if $values.org -}}
{{- if not $values.gcp.workloadIdentity.enabled }}
{{- if not $values.serviceAccountSecretProviderClass }}
{{- if not (and $env.serviceAccountSecretRefs $env.serviceAccountSecretRefs.udca) }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $udcaName }}-{{ $generatedName }}-svc-account"
  namespace: {{ include "namespace"  (dict "release" $release "values" $values) }}
type: Opaque
data:
  client_secret.json: |-
    {{- $c :=  include "tryFileContent.get" (dict "files" $files "f" (required "$env.serviceAccountPaths.udca is required!!" $env.serviceAccountPaths.udca)) }}
    {{- $c | b64enc | nindent 4 }}
{{- end }}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}
{{- end -}}