{{- $actionrs := "apigee-cassandra-restore" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $actionrs }}
  namespace: {{ include "namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $actionrs }}
subjects:
- kind: ServiceAccount
  name: {{ $actionrs }}-sa
  namespace: {{ include "namespace" . }}
