{{- if and (not .Values.gcp.workloadIdentity.enabled) (not .Values.connectAgent.serviceAccountRef) (not .Values.serviceAccountSecretProviderClass) -}}
{{- $connectAgentName := "apigee-connect-agent" -}}
{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $connectAgentName }}-{{ $generatedName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{- $c :=  include "tryFileContent.get" (dict "files" .Files "f" (required "connectAgent.serviceAccountPath is required!!" .Values.connectAgent.serviceAccountPath)) }}
    {{- $c | b64enc | nindent 4 }}
---
{{- end }}