{{- if and (not .Values.gcp.workloadIdentity.enabled) (not .Values.mart.serviceAccountRef) (not .Values.serviceAccountSecretProviderClass) -}}
{{- $martName := "apigee-mart" -}}
{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $martName }}-{{ $generatedName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{- $c :=  include "tryFileContent.get" (dict "files" .Files "f" (required "mart.serviceAccountPath is required!!" .Values.mart.serviceAccountPath)) }}
    {{- $c | b64enc | nindent 4 }}
---
{{- end }}