{{- if and (not .Values.gcp.workloadIdentity.enabled) (not .Values.udca.serviceAccountRef) (not .Values.serviceAccountSecretProviderClass) -}}
{{- $udcaName := "apigee-udca" -}}
{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $udcaName }}-{{ $generatedName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{- $c :=  include "tryFileContent.get" (dict "files" .Files "f" (required "udca.serviceAccountPath is required!!" .Values.udca.serviceAccountPath)) }}
    {{- $c | b64enc | nindent 4 }}
---
{{- end }}