{{- if and (not .Values.gcp.workloadIdentity.enabled) (not .Values.watcher.serviceAccountRef) (not .Values.serviceAccountSecretProviderClass) -}}
{{- $watcherName := "apigee-watcher" -}}
{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $watcherName }}-{{ $generatedName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{ include "tryFileContent.get" (dict "files" $.Files "f" (required "watcher.serviceAccountPath is required!!" .Values.watcher.serviceAccountPath)) | b64enc | nindent 4 }}
{{- end }}