{{- $actionbk := "apigee-cassandra-backup" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $actionbk }}
  namespace: {{ include "namespace" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $actionbk }}
subjects:
- kind: ServiceAccount
  name: {{ $actionbk }}-sa
  namespace: {{ include "namespace" . }}
