{{- $fluentdLoggerName := "apigee-logger" -}}
{{- if not .Values.gcp.workloadIdentity.enabled  -}}
{{- if and .Values.logger.enabled (not .Values.logger.serviceAccountRef) (not .Values.serviceAccountSecretProviderClass) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fluentdLoggerName }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  client_secret.json: |-
    {{- $c := include "tryFileContent.get" (dict "files" .Files "f" (required ".logger.serviceAccountPath is required!!" .Values.logger.serviceAccountPath)) }}
    {{- $c | b64enc | nindent 4 }}
{{- end }}
{{- end }}