{{- $name := "guardrails" }}
{{- if not (or .Values.cassandra.auth.secret .Values.cassandra.auth.secretProviderClass )}}
apiVersion: v1
kind: Secret
metadata:
  name: apigee-datastore-{{ $name }}-creds
  namespace: {{ include "namespace" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
type: Opaque
data:
  jmx.user: "{{ b64enc .Values.cassandra.auth.jmx.username }}"
  jmx.password: "{{ b64enc .Values.cassandra.auth.jmx.password }}"
{{- end }}
