{{- $name := "guardrails" }}
apiVersion: v1
kind: Pod
metadata:
  name: apigee-hybrid-helm-guardrail-datastore
  namespace: {{ include "namespace" . }}
  annotations:
    helm.sh/hook: pre-install,pre-upgrade
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    {{- with .Values.cassandra.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    app: apigee-hybrid-helm-guardrail
spec:
  hostNetwork: {{ .Values.cassandra.hostNetwork }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.nodeSelector }}
  affinity:
    {{- include "nodeAffinity.data" . | nindent 4 }}
  {{- end }}
  {{- $t := default .Values.tolerations .Values.guardrails.tolerations }}
  {{- with $t }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  securityContext:
    runAsNonRoot: true
    runAsUser: {{ .Values.apigeeUserID }}
    runAsGroup: {{ .Values.apigeeGroupID }}
  serviceAccountName: apigee-cassandra-guardrails-sa
  containers:
    - name: apigee-hybrid-helm-guardrail-container
      image: {{ include "container.image" (dict "hub" .Values.hub "o" .Values.guardrails "n" "apigee-watcher") }}
      imagePullPolicy: {{ .Values.guardrails.image.pullPolicy }}
      command: ['/helmguardrails']
      env:
      - name: POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      - name: COMPONENT
        value: "datastore"
      - name: CHECKPOINT
      {{- if .Values.checkpoint }}
        value: {{ .Values.checkpoint }}
      {{- else }}
        value: "pre-install"
      {{- end }}
      - name: APIGEE_ENDPOINT
        value: {{ .Values.contractProvider}}
      - name: DATACENTER
        value: {{ .Values.cassandra.datacenter }}
      {{- if .Values.cassandra.multiRegionSeedHost }}
      - name: MULTIREGIONSEEDHOST
        value: {{ .Values.cassandra.multiRegionSeedHost }}
      {{- end }}
      {{- if .Values.cassandra.auth.secretProviderClass }}
      - name: CASSANDRA_JMX_USERNAME_PATH
        value: /opt/apigee/externalsecrets/jmxUsername
      - name: CASSANDRA_JMX_PASSWORD_PATH
        value: /opt/apigee/externalsecrets/jmxPassword
      {{- else }}
      - name: APIGEE_JMX_USER
        valueFrom:
          secretKeyRef:
            {{- if .Values.cassandra.auth.secret }}
            name: {{ .Values.cassandra.auth.secret }}
            {{- else }}
            name: apigee-datastore-{{ $name }}-creds
            {{- end }}
            key: jmx.user
      - name: APIGEE_JMX_PASSWORD
        valueFrom:
          secretKeyRef:
            {{- if .Values.cassandra.auth.secret }}
            name: {{ .Values.cassandra.auth.secret }}
            {{- else }}
            name: apigee-datastore-{{ $name }}-creds
            {{- end }}
            key: jmx.password
      {{- end }}
      {{- if .Values.httpProxy }}
      {{- if .Values.httpProxy.username }}
      - name: {{ lower .Values.httpProxy.scheme }}_proxy
        value: {{ lower .Values.httpProxy.scheme }}://{{ quote .Values.httpProxy.username }}:{{ quote .Values.httpProxy.password }}@{{ .Values.httpProxy.host }}:{{ .Values.httpProxy.port }}
      {{- else }}
      - name: {{ lower .Values.httpProxy.scheme }}_proxy
        value: {{ lower .Values.httpProxy.scheme }}://{{ .Values.httpProxy.host }}:{{ .Values.httpProxy.port }}
      {{- end }}
      {{- end }}
      volumeMounts:
      - name: tls-volume
        readOnly: true
        mountPath: /opt/apigee/ssl
      {{- if .Values.cassandra.auth.secretProviderClass }}
      - name: apigee-external-secrets
        mountPath: /opt/apigee/externalsecrets
        readOnly: true
      {{- end }}
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        capabilities:
          drop:
          - ALL
      {{- with .Values.guardrails.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumes:
  - name: tls-volume
    secret:
      secretName: "apigee-datastore-guardrails-tls"
  {{- if .Values.cassandra.auth.secretProviderClass }}
  - name: apigee-external-secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: {{ .Values.cassandra.auth.secretProviderClass }}
  {{- end }}
  restartPolicy: Never
  terminationGracePeriodSeconds: 0
