{{- $actionrs := "apigee-cassandra-restore"}}
{{- $secretKey := "dbbackup_key.json" }}
{{- if .Values.cassandra.restore.enabled }}
{{- if not .Values.serviceAccountSecretProviderClass }}
{{- if or (.Values.cassandra.restore.serviceAccountPath) (.Values.cassandra.backup.serviceAccountPath) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $actionrs }}-svc-account
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  {{ $secretKey }}: |
    {{- if .Values.cassandra.restore.serviceAccountPath }}
    {{ include "tryFileContent.get" (dict "files" $.Files "f"  (required "cassandra.restore.serviceAccountPath is required!!" .Values.cassandra.restore.serviceAccountPath)) | b64enc | nindent 4 }}
    {{- else if .Values.cassandra.backup.serviceAccountPath }}
    {{ include "tryFileContent.get" (dict "files" $.Files "f" (required "cassandra.backup.serviceAccountPath is required!!" .Values.cassandra.backup.serviceAccountPath)) | b64enc | nindent 4 }}
    {{- end }}
---
{{- end }}
{{- end }}
{{- end }}