{{- $generatedName := include "orgScopeEncodedName" (dict "name" .Values.org) -}}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ $generatedName }}-data-encryption"
  namespace: {{ include "namespace" . }}
type: Opaque
data:
  plainTextDEK: |-
  {{- if .Values.contractEncryptionKey -}}
    {{ include "validateEncryptionKey" (dict "key" .Values.contractEncryptionKey) | b64enc | b64enc | nindent 4 }}
  {{- else -}}
    {{ .Values.defaults.org.contractEncryptionKey | nindent 4 }}
  {{- end }}